### ISSUE TITLE
Design Doc

### ISSUE THREAD

**Issue by IogaMaster** [IogaMaster/dynamo#1]
# Workflow
To create a server with dynamo you follow these steps:
- create server package with a designated builder functions (these contain setup and the server's config)
- create a server with the module and pass it the package
- Setup the reverse proxy

# Usage
Creates a systemd user and services for your servers.
You can choose to run in a container or microvm
```nix
dynamo.servers."vanillaminecraft" = {
  enabled = true;
  package = (import ./minecraftserver.nix); 
  reverseProxy = {
    enabled = true;
    backend = "playit"; # playit, ngrok, cloudflare
    # token = ""; # optional for certain backends
    port = 25565;
  };
};
```

Example minecraft server package:
```nix
{...}:
buildMinecraftServer {
  name = "myvanillaserver";
  src = ./mcmanconfigpath; # This is the path to the mcman config. That way I don't need to work on minecraft compatibility
  
  # Additional setup
}
```

# Todo List:

builderFunctions:
- [x] mkGenericServer
- [x] mkMinecraftServer
- [x] mkSteamServer

Additional Features:
- [x] playit, ngrok, cloudflare (reverseProxy support)
- [x] Secrets integration

Example Servers:

- [x] Minecraft (Vanilla & modded)
- [ ] Terraria (steam)
- [ ] Satisfactory (steam)
- [ ] Palworld (steam)
- [ ] Stardew valley (steam)
- [ ] Mindustry (generic)
- [ ] Factorio (generic)
- [ ] Vintage Story (Generic)

**Comment by kinzokudev** [comment]
![Screenshot_20240310_201612_YouTube.jpg](https://github.com/IogaMaster/dynamo/assets/140647311/72434b16-843f-47d4-a74b-ef8f3abcb8ae)

**Comment by IogaMaster** [comment]
Triage over!
Initial version is done. However proxies and better mkSteamServer function are planned.

**Comment by IogaMaster** [comment]
Proxy support is complete
Example servers are left
